dal-cho/adme

- src/main/java/com/dalcho/login/controller/UserController.java
- src/main/java/com/dalcho/login/dto/SignupRequestDto.java
- src/main/java/com/dalcho/login/model/User.java
- src/main/java/com/dalcho/login/repository/UserRepository.java
- src/main/java/com/dalcho/login/security/UserDetailsServiceImpl.java
- src/main/java/com/dalcho/login/service/UserService.java
제가 작성한 코드를 해달님 코드에 적용해 봤습니다.
추가 사항은 nickname에 대한 코드들을 추가했습니다.
수정 사항은 "UserController.java" 에서 signup의 return값도 home 으로 바꿨습니다.
> [add] 닉네임추가 및 front연결 수정 [#2]

- src/main/java/com/dalcho/adme/service/RegistryService.java
> [update] 페이징 코드 주석 제거 [#45]

- src/main/java/com/dalcho/adme/service/RegistryService.java
6~10페이징 화면에서 11페이지로 넘어가는 과정 오류 발견 후 계산 변경
> [update] startPage 계산 변경 [#45]

- src/main/java/com/dalcho/adme/controller/TenSecondsController.java
- src/main/java/com/dalcho/adme/domain/TenSeconds.java
- src/main/java/com/dalcho/adme/dto/VideoDto.java
- src/main/java/com/dalcho/adme/repository/TenSecondsRepository.java
- src/main/java/com/dalcho/adme/service/TenSecondsService.java
> [add] 동영상 업로드 구현 기본코드 작성 [#34]

- src/main/java/com/dalcho/adme/controller/CommentController.java
- src/main/java/com/dalcho/adme/controller/LoginController.java
- src/main/java/com/dalcho/adme/service/CommentService.java
로그인 후 index 페이지가 아닌 다른 페이지로 접속할 경우 닉네임 값을 가져오지 못하는 현상 해결
> [add] 닉네임 값 받아오기 [#83]

- build.gradle
- src/main/java/com/dalcho/adme/controller/TenSecondsController.java
> [update] 오류나는 코드 임시 주석 처리 [#86]

- build.gradle
- src/main/java/com/dalcho/adme/controller/TenSecondsController.java
- src/main/java/com/dalcho/adme/domain/TenSeconds.java
- src/main/java/com/dalcho/adme/dto/VideoDto.java
- src/main/java/com/dalcho/adme/repository/TenSecondsRepository.java
- src/main/java/com/dalcho/adme/service/TenSecondsService.java
제가 작성한 불필요한 dependencies 설정 코드를 지우고  썸네일 설정에서 에러가 났다는 정보를 통해 일단 썸네일 생성 코드를 지웠습니다.
그리고 service, repository를 통한 DB 저장을 구현했습니다.
> [fix] file 업로드 controller 코드 수정 및 service, repository 부분 작성 [#81]

- src/main/java/com/dalcho/adme/controller/VideoController.java
- src/main/java/com/dalcho/adme/service/VideoService.java
분리하여 구현한 코드를 옮기는 과정에서 발생한 차이점을 늦게 확인하여 급히 수정하여 올립니다.
> [fix] VideoController 코드 수정 [#106]

- src/main/java/com/dalcho/adme/config/security/JwtTokenProvider.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/SignController.java
- src/main/java/com/dalcho/adme/service/Impl/UserDetailServiceImpl.java
- src/main/java/com/dalcho/adme/service/UserDetailService.java
- src/main/java/com/dalcho/adme/service/UserDetailsService.java
SecurityConfig 
- WHITE_LIST 삭제 
- comment, registry Url 접근 허용
> [fix] Security 검토 및 수정 [#145]

- src/test/java/com/dalcho/adme/serviceImpl/CommentServiceTest.java
- src/test/java/com/dalcho/adme/serviceImpl/PagingH2Test.java
- src/test/java/com/dalcho/adme/serviceImpl/RegistryPagingTest.java
- src/test/java/com/dalcho/adme/serviceImpl/RegistryServiceTest.java
- src/test/java/com/dalcho/adme/serviceImpl/UserServiceTest.java
- src/test/java/com/dalcho/adme/serviceImpl/UserVideoIntergrationTest.java
> test 코드 mock 적용

- src/main/java/com/dalcho/adme/domain/User.java
- src/main/java/com/dalcho/adme/domain/VideoFile.java
- src/main/java/com/dalcho/adme/repository/UserRepository.java
- src/main/java/com/dalcho/adme/service/Impl/CommentServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/SignServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/UserDetailServiceImpl.java
- UserRepository Optional로 변경
- User - Video 연관관계 적용중
> [add] Optional 적용 및 연관관계 설정 [#141, #142]

- src/main/java/com/dalcho/adme/controller/VideoController.java
- src/main/java/com/dalcho/adme/repository/VideoRepository.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/service/VideoService.java
> [add] Video paging 설정 [#154]

- src/main/java/com/dalcho/adme/domain/User.java
- src/main/java/com/dalcho/adme/dto/sign/SignUpRequestDto.java
- src/main/java/com/dalcho/adme/service/Impl/SignServiceImpl.java
- email 속성 추가
- email, password 규칙 추가
> [add] Security email 추가, 규칙 추가 [#158]

- src/test/java/com/dalcho/adme/serviceImpl/CommentServiceTest.java
- src/test/java/com/dalcho/adme/serviceImpl/PagingH2Test.java
- src/test/java/com/dalcho/adme/serviceImpl/RegistryPagingTest.java
- src/test/java/com/dalcho/adme/serviceImpl/UserServiceTest.java
- src/test/java/com/dalcho/adme/serviceImpl/UserVideoIntergrationTest.java
> [update] test 코드

- src/main/java/com/dalcho/adme/exception/CustomException.java
- src/main/java/com/dalcho/adme/exception/ErrorCode.java
- src/main/java/com/dalcho/adme/exception/invalid/InvalidPermissionException.java
- src/main/java/com/dalcho/adme/exception/notfound/CommentNotFoundException.java
- src/main/java/com/dalcho/adme/exception/notfound/FileNotFoundException.java
- src/main/java/com/dalcho/adme/exception/notfound/RegistryNotFoundException.java
- src/main/java/com/dalcho/adme/exception/notfound/UserNotFoundException.java
- src/main/java/com/dalcho/adme/service/Impl/CommentServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/RegistryServiceImpl.java
- Registry, Comment Exception 처리 및 Registry와 Comment에서 사용하고 있는 User Exception 을 추가했습니다.
> [add] Custom Exception 추가

- src/main/java/com/dalcho/adme/exception/CustomException.java
- src/main/java/com/dalcho/adme/exception/CustomExceptionHandler.java
- src/main/java/com/dalcho/adme/exception/ErrorResponseEntity.java
> [add] CustomExceptionHandler 추가 

- src/main/java/com/dalcho/adme/exception/CustomException.java
- src/main/java/com/dalcho/adme/exception/CustomExceptionHandler.java
> [update] 어노테이션 수정

- src/main/java/com/dalcho/adme/exception/ErrorCode.java
- src/main/java/com/dalcho/adme/exception/duplicate/UserDuplicateIdException.java
- src/main/java/com/dalcho/adme/exception/invalid/InvalidPasswordException.java
- src/main/java/com/dalcho/adme/exception/invalid/InvalidPatternException.java
- src/main/java/com/dalcho/adme/exception/invalid/InvalidTokenException.java
- src/main/java/com/dalcho/adme/exception/notfound/FileNameNotFoundException.java
- src/main/java/com/dalcho/adme/exception/notfound/FileNotFoundException.java
- src/main/java/com/dalcho/adme/service/Impl/SignServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/UserDetailServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/utils/video/MultipartFileUtils.java
새로 생성한 Exception파일
- InvalidPatternException
- InvalidPasswordException
- InvalidTokenException
- UserDuplicateIdException
- FileNotFoundException
- FileNameNotFoundException
> [add] Video/User-Exception 처리 [#160]

- src/main/java/com/dalcho/adme/exception/CustomExceptionHandler.java
- src/main/java/com/dalcho/adme/exception/ErrorCode.java
- src/main/java/com/dalcho/adme/exception/db/DatabaseErrorException.java
- src/main/java/com/dalcho/adme/service/Impl/CommentServiceImpl.java
- 기존 NullPointException으로 처리하던 것을 Custom 처리
- Error code 정리
> [add] Exception 추가

- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/VideoController.java
- src/main/java/com/dalcho/adme/domain/VideoFile.java
- src/main/java/com/dalcho/adme/dto/video/VideoRequestDto.java
- src/main/java/com/dalcho/adme/repository/VideoRepository.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/service/VideoService.java
- src/main/java/com/dalcho/adme/utils/video/MultipartFileUtils.java
> [add] TenSeconds Update,Delete 구현

- build.gradle
- src/main/java/com/dalcho/adme/controller/chat/ChatRoomController.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
- 채팅 입력하면 상대방이 채팅방에 접속해있지 않을 때 알림 띄워주기 적용
> [add] 채팅 알림 적용(SSE) [#192]

- src/main/java/com/dalcho/adme/controller/VideoController.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/service/VideoService.java
- src/test/java/com/dalcho/adme/serviceImpl/UserVideoIntergrationTest.java
> [add] Video id로 조회 [#197]

- src/main/java/com/dalcho/adme/config/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/dalcho/adme/config/security/JwtAuthenticationFilter.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/SignController.java
- src/main/java/com/dalcho/adme/controller/VideoController.java
- src/main/java/com/dalcho/adme/dto/video/VideoResponseDto.java
- src/main/java/com/dalcho/adme/dto/video/VideoResultDto.java
- src/main/java/com/dalcho/adme/service/Impl/SignServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/service/VideoService.java
- src/main/resources/application.properties
- cors 문제로 테스트 환경에서의 세팅
- video ajax 통신과정에서 발생하는 수정사항
> [add] 로그인,회원가입 & Video 추가 및 수정 [#196]

- build.gradle
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
> [update] 파일 코드 변경 [#202]

- build.gradle
- src/main/java/com/dalcho/adme/config/RedisConfig.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/oauth2/CustomOAuthService.java
- src/main/java/com/dalcho/adme/oauth2/OAuth2Attribute.java
- src/main/java/com/dalcho/adme/oauth2/OAuth2SuccessHandler.java
- src/main/java/com/dalcho/adme/oauth2/Oauth2FailureHandler.java
- src/main/java/com/dalcho/adme/oauth2/util/UserMapper.java
- src/main/java/com/dalcho/adme/repository/UserRepository.java
- src/main/java/com/dalcho/adme/service/Impl/RedisService.java
- src/main/java/com/dalcho/adme/service/RegistryService.java
- oauth2 적용
- redis 적용
- 이후 chat 파일에 redis 적용할 예정
> [기능 추가] oauth2 + redis 적용

- src/main/java/com/dalcho/adme/dto/comment/CommentResponseDto.java
- comment 시간 설정 위해 modifiedAt 추가
> [update] dto [#211]

- src/main/java/com/dalcho/adme/dto/registry/RegistryResponseDto.java
- src/main/java/com/dalcho/adme/oauth2/OAuth2SuccessHandler.java
- src/main/java/com/dalcho/adme/service/Impl/RegistryServiceImpl.java
- getBoards에서 boardList에 담길때 title, idx만 담기도록 수정
- oauth2 로그인 할 때 cookie 적용
> [코드 수정] cookie, registry

- src/main/java/com/dalcho/adme/controller/CommentController.java
- src/main/java/com/dalcho/adme/service/CommentService.java
- src/main/java/com/dalcho/adme/service/Impl/CommentServiceImpl.java
- src/test/java/com/dalcho/adme/serviceImpl/CommentServiceTest.java
- parameter 값 중 dto 제거
- test 코드 수정
> [delete] dto 제거 [#215]

- src/main/java/com/dalcho/adme/controller/VideoController.java
- src/main/java/com/dalcho/adme/dto/video/VideoPagingDto.java
- src/main/java/com/dalcho/adme/dto/video/VideoResponseDto.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/service/VideoService.java
- 페이징 방법 소연님과 같은 방법으로 진행하여 myPage에서 동작할 수 있게 변경했습니다.
> [update] Video Paging 방법 변경

- src/main/java/com/dalcho/adme/config/RedisConfig.java
- src/main/java/com/dalcho/adme/dto/registry/PagingDto.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/RedisService.java
- src/main/java/com/dalcho/adme/service/Impl/RegistryServiceImpl.java
- chat 기존 코드 refactoring
- paging 코드에 totalPage추가
> [코드 수정] chat

- src/main/java/com/dalcho/adme/controller/VideoController.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/service/VideoService.java
> [update] Video 게시글 삭제시 권한 확인

- .github/workflows/gradle.yml
- Dockerfile
- EC2 생성
- gitActions 배포 스크립트 설정
- secret 키 설정
- dockerfile 수정
> [add] gitActions 배포 스크립트 작성

- src/main/java/com/dalcho/adme/config/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/dalcho/adme/config/security/JwtAuthenticationFilter.java
- src/main/java/com/dalcho/adme/config/security/JwtTokenProvider.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/HtmlController.java
- src/main/java/com/dalcho/adme/controller/chat/ChatController.java
- src/main/java/com/dalcho/adme/controller/chat/ChatRoomController.java
- src/main/java/com/dalcho/adme/controller/chat/WebSocketEventListener.java
- src/main/java/com/dalcho/adme/domain/User.java
- src/main/java/com/dalcho/adme/oauth2/CustomOAuthService.java
- src/main/java/com/dalcho/adme/oauth2/OAuth2Attribute.java
- src/main/java/com/dalcho/adme/oauth2/OAuth2SuccessHandler.java
- src/main/java/com/dalcho/adme/oauth2/util/UserMapper.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/RedisService.java
- src/main/java/com/dalcho/adme/service/Impl/UserDetailServiceImpl.java
- src/main/resources/application.properties
- form login 및 소셜 로그인 적용 완료
- 소셜 로그인 네이버 제거
> [코드 수정] form login & oauth2 login

- src/main/java/com/dalcho/adme/AdmeApplication.java
- src/main/java/com/dalcho/adme/config/AsyncConfig.java
- src/main/java/com/dalcho/adme/config/JpaAuditingConfig.java
- src/main/java/com/dalcho/adme/controller/RegistryController.java
- src/main/java/com/dalcho/adme/controller/VideoController.java
- src/main/java/com/dalcho/adme/domain/VideoFile.java
- src/main/java/com/dalcho/adme/dto/PagingDto.java
- src/main/java/com/dalcho/adme/dto/PagingResult.java
- src/main/java/com/dalcho/adme/service/Impl/RegistryServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/service/RegistryService.java
- src/main/java/com/dalcho/adme/service/VideoService.java
- PagingDto 안쓰는 메소드 수정
- JpaConfig 분리
- VideoFile 게시글 주인 확인
> [update] PagingDto 수정 & JpaConfig 분리 & videoFile 권한확인 추가

- build.gradle
- src/main/java/com/dalcho/adme/repository/CommentRepository.java
- src/main/java/com/dalcho/adme/repository/RegistryRepository.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
> [코드 수정] gson

- src/main/java/com/dalcho/adme/config/security/JwtAuthenticationFilter.java
- src/main/java/com/dalcho/adme/controller/CommentController.java
- src/main/java/com/dalcho/adme/controller/RegistryController.java
- src/main/java/com/dalcho/adme/controller/SignController.java
- src/main/java/com/dalcho/adme/service/CommentService.java
- src/main/java/com/dalcho/adme/service/Impl/CommentServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/RegistryServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/UserDetailServiceImpl.java
- src/main/java/com/dalcho/adme/service/RegistryService.java
- filter  oauth2 로그인 if문 수정
- User → UserDetails 수정
- pw 값 → ""로 변경
> [코드 수정] 로그인 정보 가져오기

- src/main/java/com/dalcho/adme/config/security/JwtTokenProvider.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/CommentController.java
- src/main/java/com/dalcho/adme/controller/RegistryController.java
- src/main/java/com/dalcho/adme/controller/SignController.java
- src/main/java/com/dalcho/adme/domain/Registry.java
- src/main/java/com/dalcho/adme/service/Impl/CommentServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/RegistryServiceImpl.java
- src/main/java/com/dalcho/adme/service/RegistryService.java
- registry url 수정 및 update api 추가
- comment update 수정
> [코드 수정] 게시글 및 댓글 update

- src/main/java/com/dalcho/adme/config/StompHandler.java
- src/main/java/com/dalcho/adme/dto/LastMessage.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
- 채팅 파일에 날짜 추가
- 당일에 작성한 채팅이 아닌경우 "날짜 + 시간" 출력
- 당일에 작성한 채팅인 경우 "시간"만 출력
> [코드 수정] 채팅 파일 날짜 추가

- build.gradle
- src/main/java/com/dalcho/adme/common/CommonResponse.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/SignController.java
- src/main/java/com/dalcho/adme/dto/sign/SignInResultDto.java
- src/main/java/com/dalcho/adme/exception/CustomException.java
- src/main/java/com/dalcho/adme/exception/invalid/InvalidPatternException.java
- src/main/java/com/dalcho/adme/service/Impl/SignServiceImpl.java
- src/test/java/com/dalcho/adme/service/VideoServiceTest.java
- 쿠키 방식 삭제 
- 이메일, 비밀번호 패턴 오류 출력
> [기능 변경 및 추가] 쿠키 삭제 및 이메일,비밀번호 패턴 오류 출력

- src/main/java/com/dalcho/adme/dto/video/VideoMultipartFile.java
- src/main/java/com/dalcho/adme/service/Impl/VideoServiceImpl.java
- src/main/java/com/dalcho/adme/utils/video/FfmpegUtils.java
Ffmpeg setTime 값에 따라 동영상 편집 기능으로 수정
> [기능수정] FFmpeg setTime 값 적용

- Dockerfile
- src/main/java/com/dalcho/adme/config/FileConfig.java
- src/main/java/com/dalcho/adme/manager/AbstractFileManager.java
- src/main/java/com/dalcho/adme/manager/OriginalFileManager.java
- src/main/java/com/dalcho/adme/manager/TenFileManager.java
- src/main/java/com/dalcho/adme/manager/ThumbnailFileManager.java
- src/main/java/com/dalcho/adme/utils/video/FfmpegUtils.java
- src/main/java/com/dalcho/adme/utils/video/LocalFileUtils.java
- src/main/java/com/dalcho/adme/utils/video/S3Utils.java
- src/test/java/com/dalcho/adme/serviceImpl/UserVideoIntergrationTest.java
- root 경로 설정 : EC2 - Docker의 경로에 OriginalVideo,TenVideo,Thumbnail 폴더 생성 및 경로 설정
- DockerFile 수정 : EC2 - Docker에 ffmpeg 동영상 인코더 프로그램 설치 커멘드 작성
> [기능수정] root 경로 설정 & Dockerfile 수정

- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
social login이 동작하지 않아 security 수정
> [코드 추가] oauth2 오류 수정

- src/main/java/com/dalcho/adme/config/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/chat/ChatController.java
- src/main/java/com/dalcho/adme/controller/chat/ChatRoomController.java
- src/main/java/com/dalcho/adme/controller/chat/WebSocketEventListener.java
- src/main/java/com/dalcho/adme/dto/chat/ChatMessage.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/RedisService.java
- redis cache로 sessionId를 통해 token을 저장하기 위해 코드 추가
- front에서 시간을 받아와서 back에 저장
> [코드 수정] 채팅 수정

- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/SignController.java
- src/main/java/com/dalcho/adme/oauth2/OAuth2SuccessHandler.java
- kakao login 성공(db 저장 확인)
- queryString에 token, nickname 추가
> [코드 수정] oauth2 수정 

- src/main/java/com/dalcho/adme/config/RedisPublisher.java
- src/main/java/com/dalcho/adme/config/RedisSubscriber.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/RegistryController.java
- src/main/java/com/dalcho/adme/controller/chat/ChatRoomController.java
- src/main/java/com/dalcho/adme/dto/LastMessage.java
- src/main/java/com/dalcho/adme/exception/ErrorCode.java
- src/main/java/com/dalcho/adme/exception/invalid/InvalidNicknameException.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/SignServiceImpl.java
- 관리자 채팅 동작 확인
- 특정 nickname 사용못하게 막음
- CORS 수정 
- 관리자 페이지 security 설정
> [코드 수정] 관리자 페이지 수정  

- src/main/java/com/dalcho/adme/config/security/JwtAuthenticationFilter.java
- src/main/java/com/dalcho/adme/config/security/SecurityConfiguration.java
- src/main/java/com/dalcho/adme/controller/chat/ChatController.java
- src/main/java/com/dalcho/adme/controller/chat/ChatRoomController.java
- src/main/java/com/dalcho/adme/controller/chat/WebSocketEventListener.java
- src/main/java/com/dalcho/adme/dto/chat/ChatMessage.java
- src/main/java/com/dalcho/adme/dto/chat/ChatRoomDto.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
- src/main/java/com/dalcho/adme/service/Impl/RegistryServiceImpl.java
- Transactional 추가
- 채팅&알람 실행 시 nickname 대신 권한으로 관리자 와 일반 사용자 구분
- SSE 수정
- CORS 수정
> [코드 수정] 공감공간 게시글 

- src/main/java/com/dalcho/adme/dto/chat/ChatRoomDto.java
- src/main/java/com/dalcho/adme/service/Impl/ChatServiceImpl.java
> [코드 수정] Dto 필드 중복 제거
